version: '3.8'

services:
  app:
    image: python:3.13.14-trixie
    command: "bash -c 'pip install  -r requirements.txt && opentelemetry-instrument python -m debugpy --listen 0.0.0.0:5678 runserver.py'"
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 8080:8080
      - 5678:5678
    depends_on:
      - jaeger
      - db
    environment:
      OTEL_SERVICE_NAME: flask-api
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: none

  front:
    build:
      context: ./front
      dockerfile: .dockerfile
    command: npm run start
    working_dir: /app
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - 5173:5173
    depends_on:
      - app

  jaeger:
    image: jaegertracing/jaeger:latest
    ports:
      - "16686:16686"

  db:
    image: postgres:13.7
    environment:
      # Si c'est un container de prod -> mots de largement passe insuffisant
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: app
      POSTGRES_DB: app

    ports:
      - '5435:5432'

    volumes:
      - app-volume:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=Test1234=
      - PGADMIN_LISTEN_PORT=8081
    ports:
      # 8081 -> PGADMIN_LISTEN_PORT
      # le port à droite doit obligatoirement être lié au PGADMIN_LISTEN_PORT
      # ou 80 par défaut
      # Toute modification de ports doit être suivie d'un :
      # docker compose up SERVICE_NAME -d
      - 8081:8081

    volumes:
      - pgadmin-volume:/var/lib/pgadmin
      - ./pgadmin_config/servers.json:/pgadmin4/servers.json

volumes:
  app-volume:
  pgadmin-volume:
